name: Build RimWorldOfMagic DLL

on:
  push:
    paths:
      - 'RimWorldOfMagic/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: |
        cd RimWorldOfMagic
        msbuild RimWorldOfMagic.sln /p:Configuration=Release

    - name: Upload DLLs
      uses: actions/upload-artifact@v4
      with:
        name: RimWorldOfMagic_DLLs
        path: |
          RimWorldOfMagic/**/bin/Release/*.dll
